### ISSUE TITLE
Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by ghost** [annotorious/annotorious-v1#184]
Hi all,

I've incorporated Annotorious into my own application in which images are constantly being rotated. Each image is made annotatable using anno.makeAnnotatable and I save any annotations in my own data storage. I am running into a problem whenever I try to delete or edit annotations. Every time I do so, I receive the following error:

```
Uncaught TypeError: Cannot read property 'type' of undefined
    at http://localhost:45000/js/annotorious.min.js:214:100
    at Array.forEach (native)
    at C (http://localhost:45000/js/annotorious.min.js:5:1049)
    at lf.s.mb (http://localhost:45000/js/annotorious.min.js:214:36)
    at nf (http://localhost:45000/js/annotorious.min.js:213:24)
    at HTMLCanvasElement.<anonymous> (http://localhost:45000/js/annotorious.min.js:210:358)
    at vc.s.handleEvent (http://localhost:45000/js/annotorious.min.js:72:699)
    at Fc (http://localhost:45000/js/annotorious.min.js:77:243)
    at HTMLCanvasElement.Ac (http://localhost:45000/js/annotorious.min.js:79:246)
    at HTMLCanvasElement.<anonymous> (http://localhost:45000/js/annotorious.min.js:73:349)
```

Does anyone have any ideas what may be causing this?

**Comment by ghost** [comment]
Any help on this? Kind of frustrating to not have any response after 8 days with an issue that seems to be a bug.

**Comment by headkit** [comment]
It happens when you have two keypoints in the exact same position.

**Comment by headkit** [comment]
Or something else... I have the same issue right now. Any news here? Thnx!

**Comment by headkit** [comment]
Same error but it is thrown when I create a new annotation and after that when I move the mouse around the annotation-area (onMouseMove). When I leave the area the new annotation is gone.

**Comment by headkit** [comment]
solved my problem. in my case I added attributes to the geometry-object which was a bad idea...

**Comment by huaxiachenli** [comment]
I have the same issue right now. Any news here? Thnx!
