### ISSUE TITLE
ReferenceError: "anno is not defined"

### ISSUE THREAD

**Issue by BALAMRGAN** [annotorious/annotorious-v1#192]
Hi..

I have added "angular-annotorious.js" and the css file too. But when am running my application am getting the following error

ReferenceError: anno is not defined
    at getAnnotorious (http://localhost:8000/app/js/base.js:60249:13)
    at Object.makeAnnotatable (http://localhost:8000/app/js/base.js:60456:20)
    at activate (http://localhost:8000/app/js/app.js:8278:23)
    at caseviewcontroller (http://localhost:8000/app/js/app.js:8272:3)
    at invoke (http://localhost:8000/app/js/base.js:13658:17)
    at Object.instantiate (http://localhost:8000/app/js/base.js:13666:27)
    at http://localhost:8000/app/js/base.js:18222:28
    at http://localhost:8000/app/js/base.js:47121:28
    at invokeLinkFn (http://localhost:8000/app/js/base.js:17858:9)
    at nodeLinkFn (http://localhost:8000/app/js/base.js:17358:11) <div ui-view="" autoscroll="false" ng-class="app.viewAnimation" class="content-wrapper ng-scope">

added html like this.
"img id="aimage" src="http://annotorious.github.io/img/splash-image-1.jpg" data-original="stable-identifier-for-image" annotorious-annotate"

But am getting error. How to fix it.

**Comment by viswanath-puttagunta** [comment]
Hello All,

Is there a tip on how to resolve this?

Any help would be greatly appreciated.

Regards,
Vish

**Comment by gtopsis** [comment]
You need both annotorious.js (anno object is defined there) and angular-annotorious.js.

**Comment by diazenal** [comment]
const anno = window['anno'];

**Comment by BALAMRGAN** [comment]
It worked after adding annotorious.min.js
