### ISSUE TITLE
[doc] [wiki] Update test procedure

### ISSUE THREAD

**Issue by dereckson** [annotorious/annotorious-v1#92]
https://github.com/annotorious/annotorious/wiki/Developers offers the following information to test the current code:

(1) java -jar plovr/plovr.jar serve standalone.json
(2) simply open test/image/index.html for a test page that uses it.

When opening this file: Unknown configuration id: image
When requesting the list of tests availables: No tests for annotorious.

**Comment by rsimon** [comment]
The test/image/index.html page is not an automated test page. (I guess it should be called an "example page" instead... fixed that in the Wiki!) It's a page that lets you play with Annotorious (manually) while you are working on it.

The procedure described above works fine on my end (Windows, Linux - Chrome, FF). Do you see the error message on the JavaScript console? On the terminal from which you started Plovr? From where/how do you request a list of tests? (There is a separate test page in the /qunit subfolder which has some automated tests, BTW.) Can you describe the steps you take in a little more detail?

Cheers,
R

**Comment by dereckson** [comment]
Environment: FreeBSD 8, Java 1.6  (OpenJDK)

[ test/image/index.html ]

In the browser:
An output with only the following text, without HTML embeddeing:
"Unknown configuration id: image"

In the console log, there is indeed an exception thrown:
Dec 21, 2013 8:50:17 AM com.google.common.io.Closeables close
WARNING: IOException thrown while closing Closeable.
java.io.IOException: insufficient bytes written to stream
        at sun.net.httpserver.FixedLengthOutputStream.close(FixedLengthOutputStream.java:89)
        at sun.net.httpserver.PlaceholderOutputStream.close(ExchangeImpl.java:421)
        at com.google.common.io.Closeables.close(Closeables.java:80)
        at com.google.common.io.Closeables.closeQuietly(Closeables.java:99)
        at org.plovr.AbstractGetHandler.handle(AbstractGetHandler.java:96)
        at org.plovr.CompilationServer$1.handle(CompilationServer.java:124)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:83)
        at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:86)
        at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:589)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:83)
        at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:561)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:679)

[ List of tests ]

When I go to http://localhost:9810/ I see the following output:

List of configs loaded in plovr
annotorious

```
Compilation output
List of files in compilation
List of tests
Test runner
```

I followed the link "List of tests", pointing to http://localhost:9810/test/annotorious/list
